---
- hosts: masters
  become: yes
  roles:
    - tools
    - containerd
    - crictl
    - k8s-prep
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - local-pods.yaml
        - multus-daemonset.yaml
        - netattach.yaml
        - pod.yaml
        - two-pods.yaml
