---
- hosts: masters
  become: yes
  roles:
    - tools
    - containerd
    - crictl
    - k8s-prep
    - k8s
- hosts: remote
  become: yes
  tasks:
    - name: debugger
      ansible.builtin.apt:
        name: gdb
        update_cache: yes
    - name: files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/{{ item }}
        owner: root
        group: root
        mode: '0644'
      with_list:
        - crasher.c
        - crasher-deploy.yaml
        - nginx-selector.yaml
        - nginx-typo.yaml
        - postgres-fixed.yaml
        - postgres-misconfig.yaml
        - sleep-multiple.yaml
        - sleep-sensible.yaml
